<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="retryCases"
           tests="5"
           failures="1"
           errors="0"
           skipped="3"
           time="0.256">
  <properties />
            <testcase name="test_2" time="0.065" classname="retryLogic.MyCases">
                <failure type="java.lang.AssertionError"
                  message="expected [false] but found [true]"
              >
<![CDATA[java.lang.AssertionError: expected [false] but found [true]
  org.testng.Assert.fail(Assert.java:96)
  org.testng.Assert.failNotEquals(Assert.java:776)
  org.testng.Assert.assertEqualsImpl(Assert.java:137)
  org.testng.Assert.assertEquals(Assert.java:118)
  org.testng.Assert.assertEquals(Assert.java:568)
  org.testng.Assert.assertEquals(Assert.java:578)
  retryLogic.MyCases.test_2(MyCases.java:41)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
  org.testng.internal.Invoker.retryFailed(Invoker.java:838)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1009)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
  org.testng.TestRunner.privateRun(TestRunner.java:648)
  org.testng.TestRunner.run(TestRunner.java:505)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
  org.testng.SuiteRunner.run(SuiteRunner.java:364)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
  org.testng.TestNG.runSuites(TestNG.java:1049)
  org.testng.TestNG.run(TestNG.java:1017)
  org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
  org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
  org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
      </failure>

          </testcase>
  
            <testcase name="test_2" time="0.0" classname="retryLogic.MyCases">
          <skipped />
    </testcase>
            <testcase name="test_2" time="0.0" classname="retryLogic.MyCases">
          <skipped />
    </testcase>
            <testcase name="test_2" time="0.0" classname="retryLogic.MyCases">
          <skipped />
    </testcase>
  
            <testcase name="test_1" time="0.018" classname="retryLogic.MyCases" />
      
</testsuite>
